# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true # make the workflow fail on high severity issues
confirm: true #  automatic confirmation of multiple file submissions (equivalent to --yes)

analyze:
  mode: standard
  async: true
  create-group: true
  group-name: "@crossbell/crossbell-contracts"
  solc: 0.8.18
  remappings:
    - "@openzeppelin/=node_modules/@openzeppelin/"
    - "ds-test/=lib/forge-std/lib/ds-test/src/"
    - "forge-std/=lib/forge-std/src/"
  targets:
    - contracts/Web3EntryBase.sol
    - contracts/Linklist.sol
    - contracts/misc/NewbieVilla.sol
    - contracts/misc/Tips.sol
    - contracts/misc/Periphery.sol
    - contracts/misc/TipsWithFee.sol
    - contracts/misc/TipsWithConfig.sol