#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint
echo "Running lint"
yarn lint

# unit test
echo "Running test"
yarn test

# storage-layout check
echo "Running storage-layout check"
yarn storage-layout

# solhint
echo "Running solhint"
yarn solhint