name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Update Modules
        run: yarn sync
      - name: Run Tests
        run: FOUNDRY_PROFILE=ci yarn test
      - name: Run Coverage
        run: forge coverage --report lcov
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install lcov
      - name: Remove unwanted files
        run: lcov --remove ./lcov.info -o ./lcov.info.pruned 'test/*' \
                  'scripts/*' 'contracts/mocks/*' 'contracts/misc/Periphery.sol' \
                  'contracts/libraries/*' 'contracts/base/*' \
                  'contracts/modules/link/*' 'contracts/modules/mint/*' \
                  'contracts/upgradeability/*'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./lcov.info.pruned
          name: grappa-coverage
          verbose: true
